### ISSUE TITLE
fazer 4.1 Controle de cadastro de medicamentos

### ISSUE THREAD

**Issue by thiagolarangeiras** [thiagolarangeiras/satc-backend-projeto-final#2]
[Descrito aqui README.md 4.1](https://github.com/thiagolarangeiras/satc-backend-projeto-final/blob/main/README.md#41-controle-de-cadastro-de-medicamentos)

Atualizar a definição no README.md conforme implemente

**Comment by thiagolarangeiras** [comment]
Atualizado conforme ajustes de ebf04684ad8f364350ec93836dd48c04eef428bc

**Comment by pauloDalponte** [comment]
Criado

**Comment by thiagolarangeiras** [comment]
commit 9a9fd34a6b2a4061e52ad3f9c8d072bedeeea2ce

**Comment by thiagolarangeiras** [comment]
Ajustes em af251835e1a84fabcff0825d44d99c08f69c51f2

**Comment by thiagolarangeiras** [comment]
feito

**Comment by thiagolarangeiras** [comment]
feito
