### ISSUE TITLE
fazer 4.2 Controle de cadastro de médicos e pacientes

### ISSUE THREAD

**Issue by thiagolarangeiras** [thiagolarangeiras/satc-backend-projeto-final#3]
[Descrito aqui README.md 4.2](https://github.com/thiagolarangeiras/satc-backend-projeto-final?tab=readme-ov-file#42-controle-de-cadastro-de-m%C3%A9dicos-e-pacientes)

Atualizar a definição no README.md conforme implemente

**Comment by pauloDalponte** [comment]
Criado

**Comment by thiagolarangeiras** [comment]
commit 9a9fd34a6b2a4061e52ad3f9c8d072bedeeea2ce

**Comment by thiagolarangeiras** [comment]
Ajuste em 7166bfdfca0837573c7521a4295a576453eb2837

**Comment by thiagolarangeiras** [comment]
feito
