### ISSUE TITLE
fazer 4.4 Controle de Consultas para Paciente

### ISSUE THREAD

**Issue by thiagolarangeiras** [thiagolarangeiras/satc-backend-projeto-final#5]
[Descrito aqui](https://github.com/thiagolarangeiras/satc-backend-projeto-final?tab=readme-ov-file#44-controle-de-consultas-para-paciente)

Atualizar a definição no README.md conforme implemente

**Comment by thiagolarangeiras** [comment]
atualizado

**Comment by jpdarabas** [comment]
Feito, à espera de testes

**Comment by thiagolarangeiras** [comment]
feito
